baseURL: https://www.jonmsterling.com/forest/
languageCode: en-us
title: Jon Sterling's Forest
theme: github.com/adityatelange/hugo-PaperMod

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

params:
  author: Jonathan Sterling
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Forest"

  # home-info mode
  homeInfoParams:
    title: Jon Sterling's Forest
    content: |
      {{<transclude jms-0001>}}

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

markup:
  goldmark:
    renderer:
      unsafe: true
    extension:
      footnotes: true

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
      - PWD
