name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            scheme-basic
            standalone
            mlmodern
            amsfonts
            amsmath
            zx-calculus
            tikz-cd
            l3packages
            dvisvgm
            pgf
            etoolbox

      - name: Check `latex` version
        run: latex --version

      - name: Install Forester
        run: go install git.sr.ht/~jonsterling/forester/cmd/forester@9da17881220776dfa3599e8ca3088f313388a398

      - name: Build SVGs and dependency graph using Forester
        run: ~/go/bin/forester -active-fence render-latex -input-dir content

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
